### ISSUE TITLE
EPIC(EAG): payments tables

### ISSUE THREAD

**Issue by quinn-dougherty** [quinn-dougherty/rallypoint#18]
- [x] `payments_allocation` should be added to on the `create` page (for new bounties) #25 
- ~~`payments_allocation` should also be able to be added to on preexisting bounties (by adding to a preexisting balance) #22~~ (see remark about not doing this until after EAG/MVP) 
  - ~~depends on #21~~ 
- [x] #26 
- [x] #44 
- [x] #22

**Comment by quinn-dougherty** [comment]
- [ ] `payments_allocation` should be added to on the `create` page (for new bounties) 
- [ ] `payments_allocation` should also be able to be added to on preexisting bounties (by adding to a preexisting balance)

**Comment by quinn-dougherty** [comment]
- (optional) [ ] add sql `CHECKS` in supabase to enforce business logic.

**Comment by quinn-dougherty** [comment]
For EAG milestone https://github.com/quinn-dougherty/nextjs-with-supabase/milestone/1 this is effectively playmoney, which means no withdrawals and no deposits. Allocations and sending money to others is still important.
