### ISSUE TITLE
EPIC(MVP): tags

### ISSUE THREAD

**Issue by quinn-dougherty** [quinn-dougherty/rallypoint#54]
- [x] tag search (grep) for adding tags
  - [x] allow tagging on create post #55 
  - [x] allow tagging on preexisting posts #56 
- [x] tag search (grep with filter) for browsing posts 
-  tags themselves: ~~a postgres enum, or~~ string? 
  - [x] only allow admins to add new tags
